import CustomerReview from "@/components/ui/customerreview";
import OffersAndSatisfaction from "@/components/ui/offer";
import OurPromise from "@/components/ui/OurPromise";
import ProductFaq from "@/components/ui/productfaq";
import TestimonialCarousel from "@/components/ui/testimonials";
import {
  allReviews_Ejacure,
  allReviews_Electrosure,
  allReviews_Staminor,
  allReviews_Testofix,
  atGlance_Ejacure,
  atGlance_Electrosure,
  atGlance_Staminor,
  atGlance_Testofix,
  customHero_Ejacure,
  customHero_Electrosure,
  customHero_Staminor,
  customHero_Testofix,
  howToUse_Ejacure,
  howToUse_Electrosure,
  howToUse_Staminor,
  howToUse_Testofix,
  ingredients_Ejacure,
  ingredients_Electrosure,
  ingredients_Staminor,
  ingredients_Testofix,
  keyBenefits_Ejacure,
  keyBenefits_Electrosure,
  keyBenefits_Staminor,
  keyBenefits_Testofix,
  doctorProfile_Ejacure,
  whoItsFor_Ejacure,
  whoItsFor_Electrosure,
  whoItsFor_Staminor,
  whoItsFor_Testofix,
  faqs_Ejacure,
  faqs_Electrosure,
  faqs_Staminor,
  faqs_Testofix,
  offers_Ejacure,
  offers_Electrosure,
  offers_Staminor,
  offers_Testofix,
  promises_Ejacure,
  promises_Electrosure,
  promises_Staminor,
  promises_Testofix,
  reviews_Ejacure,
  satisfaction_Ejacure,
  satisfactionData_Electrosure,
  satisfactionData_Staminor,
  satisfactionData_Testofix,
  testimonials_Ejacure,
  testimonials_Electrosure,
  testimonials_Staminor,
  testimonials_testofix,
} from "@/lib/data";

export const dynamicComponent = (key: string) => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const componentObject: Record<string, any> = {
    ejacure: {
      offer: OffersAndSatisfaction,
      offerProps: offers_Ejacure,
      satisfactionProps: satisfaction_Ejacure,
      successStories: TestimonialCarousel,
      successStoriesProps: testimonials_Ejacure,
      customHero: customHero_Ejacure,
      keyBenefits: keyBenefits_Ejacure,
      atGlance: atGlance_Ejacure,
      doctorProfile: doctorProfile_Ejacure,
      ingredients: ingredients_Ejacure,
      howToUse: howToUse_Ejacure,
      whoItsFor: whoItsFor_Ejacure,
      faq: ProductFaq,
      faqProps: faqs_Ejacure,
      customerReview: CustomerReview,
      reviewProps: reviews_Ejacure,
      allReviewProps: allReviews_Ejacure,
      cta: OurPromise,
      ctaProps: promises_Ejacure,
      pairedHandles: ["testofix", "staminor"],
      aplusImages: [
        "/Ejacure web A+ images 2.jpg.jpg",
        "/Ejacure web A+ images 3.jpg.jpg",
        "/Ejacure web A+ images 4.jpg.jpg",
        "/Ejacure web A+ images 5.jpg.jpg",
        "/Ejacure web A+ images 6.jpg.jpg",
      ],
    },
    erectossure: {
      offer: OffersAndSatisfaction,
      offerProps: offers_Electrosure,
      satisfactionProps: satisfactionData_Electrosure,
      successStories: TestimonialCarousel,
      successStoriesProps: testimonials_Electrosure,
      customHero: customHero_Electrosure,
      keyBenefits: keyBenefits_Electrosure,
      atGlance: atGlance_Electrosure,
      ingredients: ingredients_Electrosure,
      howToUse: howToUse_Electrosure,
      whoItsFor: whoItsFor_Electrosure,
      faq: ProductFaq,
      faqProps: faqs_Electrosure,
      customerReview: CustomerReview,
      reviewProps: reviews_Ejacure,
      allReviewProps: allReviews_Electrosure,
      cta: OurPromise,
      ctaProps: promises_Electrosure,
      pairedHandles: ["ejacure", "staminor"],
      aplusImages: [
        "/erectosore A+ images  2.jpg.jpg",
        "/erectosore A+ images  3.jpg.jpg",
        "/erectosore A+ images  4.jpg.jpg",
        "/erectosore A+ images  5.jpg.jpg",
        "/erectosore A+ images  6.jpg.jpg",
      ],
    },
    testofix: {
      offer: OffersAndSatisfaction,
      offerProps: offers_Testofix,
      satisfactionProps: satisfactionData_Testofix,
      successStories: TestimonialCarousel,
      successStoriesProps: testimonials_testofix,
      customHero: customHero_Testofix,
      keyBenefits: keyBenefits_Testofix,
      atGlance: atGlance_Testofix,
      ingredients: ingredients_Testofix,
      howToUse: howToUse_Testofix,
      whoItsFor: whoItsFor_Testofix,
      faq: ProductFaq,
      faqProps: faqs_Testofix,
      customerReview: CustomerReview,
      reviewProps: reviews_Ejacure,
      allReviewProps: allReviews_Testofix,
      cta: OurPromise,
      ctaProps: promises_Testofix,
      pairedHandles: ["ejacure", "staminor"],
      aplusImages: [
        "/testofix A+ Images 1.jpg.jpg",
        "/testofix A+ Images 2.jpg.jpg",
        "/testofix A+ Images 3.jpg.jpg",
        "/testofix A+ Images  4.jpg.jpg",
        "/testofix A+ Images 5.jpg.jpg",
        "/testofix A+ Images 6.jpg.jpg",
      ],
    },
    staminor: {
      offer: OffersAndSatisfaction,
      offerProps: offers_Staminor,
      satisfactionProps: satisfactionData_Staminor,
      successStories: TestimonialCarousel,
      successStoriesProps: testimonials_Staminor,
      customHero: customHero_Staminor,
      keyBenefits: keyBenefits_Staminor,
      atGlance: atGlance_Staminor,
      ingredients: ingredients_Staminor,
      howToUse: howToUse_Staminor,
      whoItsFor: whoItsFor_Staminor,
      faq: ProductFaq,
      faqProps: faqs_Staminor,
      customerReview: CustomerReview,
      reviewProps: reviews_Ejacure,
      allReviewProps: allReviews_Staminor,
      cta: OurPromise,
      ctaProps: promises_Staminor,
      pairedHandles: ["ejacure", "testofix"],
      aplusImages: [], // No A+ images available yet for Staminor
    },
  };

  return componentObject[key] ?? {};
};
